name: CI

on:
  push:
    paths-ignore: [README.md]
  pull_request:
    paths-ignore: [README.md]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release BMS, Release 2013]
        include:
          - Configuration: Release BMS
            SDK: bms
          - Configuration: Release 2013
            SDK: sdk2013
    steps:
    - name: Checkout SPT
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init -j $env:NUMBER_OF_PROCESSORS SPTLib SDK\${{ matrix.SDK }}
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild /m /nologo /p:Configuration="${{ matrix.Configuration }}" spt.sln
    - name: Get SPT DLL name
      run: |
        $spt_filename = (Get-Item "${{ matrix.Configuration }}\spt*.dll").BaseName
        echo "::set-env name=spt_filename::$spt_filename"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.Configuration }} - ${{ env.spt_filename }}
        path: ${{ matrix.Configuration }}\${{ env.spt_filename }}.dll
